server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://20.127.192.215:3100/loki/api/v1/push

scrape_configs:
  - job_name: cliente
    static_configs:
      - targets:
          - localhost
        labels:
          job: cliente
          host: cliente-vm
          __path__: /app/errors.json
